server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  profiles:
    active: dev
  application:
    name: Registration Management

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    table: SCHEMA_HISTORY
    locations:
      - classpath:/db/migration
      - classpath:/db/migration-data

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


jwt:
  header: Authorization
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 15000




